repos:
  # - repo: https://github.com/python-poetry/poetry
  #   rev: '1.2.0b1'
  #   hooks:
  #     - id: poetry-check
  #     - id: poetry-lock

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: pretty-format-json
        args: ["--autofix", --no-sort-keys]
  - repo: https://github.com/pycqa/isort
    rev: '5.13.2'
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black