[tool.poetry]
name = "pyes"
version = "0.2.4"
description = ""
authors = ["Lorenzo Castellino <castellino96@gmail.com>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
ppg = {git = "ssh://git@github.com/Kastakin/ppg.git", rev = "main"}
pandas = "^1.3.5"
pyqtgraph = "^0.12.3"
PySide6 = "^6.2.2"
openpyxl = "^3.0.9"

[tool.poetry.dev-dependencies]
tbump = "^6.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
