# Uncomment this if your project is hosted on GitHub:
# github_url = "https://github.com/<user or organization>/<project>/"

[version]
current = "0.4.2"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

# For each file to patch, add a [[file]] config
# section containing the path of the file, relative to the
# tbump.toml location.
[[file]]
src = "pyproject.toml"
search = 'version = "{current_version}"'

[[file]]
src = "src/main/python/ui/PyES_about.py"
search = "PyES Version {current_version}"

[[file]]
src = "src/main/python/ui/PyES_about.ui"
search = "PyES Version {current_version}"

[[file]]
src = "src/build/settings/base.json"

[[before_commit]]
name = "Update Changelog"
cmd = "poetry run python scripts/changelog_generator.py v{current_version} v{new_version}"
