on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release Multi Platform

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release # Creates the release, assets will be added after building
        id: create_release
        uses: ncipollo/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: release_text.md
          draft: false
          prerelease: false

  build-linux:
    name: Build Ubuntu
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install fpm
        run: |
          sudo apt-get install ruby ruby-dev rubygems build-essential
          sudo gem install --no-document --minimal-deps fpm
          fpm --version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements/base.txt"
      - name: Install Python dependencies
        run: pip install -r requirements/base.txt
      - name: Run ppg
        run: |
          ppg freeze
          ppg installer
      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/PyES.deb
          asset_name: PyES-${{ github.ref }}.deb
          tag: ${{ github.ref }}
          overwrite: true

  build-macos:
    name: Build macOS
    needs: create-release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements/base.txt"
      - name: Install Python dependencies
        run: pip install -r requirements/base.txt
      - name: Run ppg
        run: |
          ppg freeze
          ppg installer
      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/PyES.dmg
          asset_name: PyES-${{ github.ref }}.dmg
          tag: ${{ github.ref }}
          overwrite: true

  build-windows:
    name: Build Windows
    needs: create-release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements/base.txt"
      - name: Install Python dependencies
        run: pip install -r requirements/base.txt
      - name: Run ppg
        run: |
          ppg freeze
          ppg installer
      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/PyESSetup.exe
          asset_name: PyES-${{ github.ref }}.exe
          tag: ${{ github.ref }}
          overwrite: true

  rollback-release:
    name: Rollback
    if: ${{ failure() }}
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Rollback
        uses: author/action-rollback@stable
        with:
          tag: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

